export const workData = [
  {
    from: '07/2024',
    to: 'Present',
    position: 'Frontend Developer',
    companyName: 'Avature',
    responsibilities: [
      'Create a responsive website using HTML, CSS, and vanilla JavaScript',
      'Collaborate with team members to define objectives, design functional features, and enhance the user experience',
      'Optimize applications for maximum speed, scalability, and cross-browser compatibility',
      'Implement UI/UX designs and ensure visual consistency across the platform',
      'Translating designs and wireframes into high-quality code',
      'Building reusable components',
      'Ensure a high standard of code quality and maintainability',
    ],
  },
  {
    from: '06/2022',
    to: '07/2024',
    position: 'Senior Support Specialist',
    companyName: 'Luxoft',
    responsibilities: [
      'Working with Service Desc tickets',
      'Taking part of integration processes',
      'Working with SQL Database',
      'Updating data via REST API',
      'Creating and maintaining custom pages',
      'Providing custom repots',
      'Helping other team members',
      'Managing users permissions',
      'Cooperating with vendor for bugs removal',
      'Analyzing and creating company processes',
    ],
  },
  {
    from: '10/2021',
    to: '06/2022',
    position: 'Junior Software Engineer',
    companyName: 'Scalefocus',
    responsibilities: [
      'Implement and test new features',
      'Create integrations between Salesforce and internal or third-party APIs and Data Sources',
      'Buld Salesforce flows and porcesses',
      'Working with Salesforce Triggers',
      'Create programming logic with Apex (Java-based OOP programming language)',
      'Create tests for the implemented logic',
      'Worknig with Salesforce database',
      'Create custom reports',
      'Create visual components',
      'Clarifying technical requirement',
      'Working with Agile methodology',
    ],
  },
  {
    from: '01/2018',
    to: '10/2021',
    position: 'Production Manager',
    companyName: 'Minerali Industriali S.r.l.',
    responsibilities: [
      'Managing a team of 15 subordinates',
      'Negotiating deliveries to customers',
      'Liaising with suppliers',
      'Providing reports to the business owners',
      'Agreeing budgets, timescales and specifications with clients and managers',
      'Optimizing the manufacturing process and lowering the cost',
      'Maintenance and monitoring the availability of spare parts',
      'Organization and implementation of scheduled repairs',
      'All other responsibilities connected to the manufacturing process',
    ],
  },
  {
    from: '11/2016',
    to: '01/2018',
    position: 'CAD Engineer',
    companyName: 'Ideal Standard International NV',
    responsibilities: [
      'Assessing project requirements',
      'Problem solving',
      'Undertaking relevant research',
      'Producing and implementing designs and test procedures',
      'Measuring the perfromance of mechanical components and devices',
      'esting, evaluating with international standards, modifying and re-testing products',
      'Writing reports and documentation',
      'Providing technical advices',
      'Analysing and interpreting data',
    ],
  },
  {
    from: '11/2014',
    to: '11/2016',
    position: 'CAD Engineer',
    companyName: 'PL Control',
    responsibilities: [
      'Assessing project requirements',
      'Agreeing budgets, timescales and specifications with clients and managers',
      'Liaising with suppliers',
      'Problem solving',
      'Undertaking relevant research',
      'Producing and implementing designs and test procedures',
      'Measuring perfromance of mechanical components, devices and engines',
      'Testing, evaluating, modifying and re-testing products',
      'Writing reports and documentation',
      'Providing technical advice',
      'Analysing and interpreting data',
    ],
  },
];
